version: "3.1"
services:
  db:
    container_name: lah_db
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - '5432:5432'
  api:
    container_name: api
    image: registry.digitalocean.com/lend-a-hand/backend
    restart: always
    ports:
      - "9000:9000"
    expose:
      - "9000"
    depends_on:
      - db
      - frontend

  frontend:
    container_name: react
    image: registry.digitalocean.com/lend-a-hand/frontend
    restart: always
    ports:
      - "3000:3000"
    expose:
      - "3000"
    depends_on:
      - api
      - chat

  chat:
    container_name: chat
    image: registry.digitalocean.com/lend-a-hand/chat-service
    ports:
      - '8080:8080'
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "6379"

  redis:
    container_name: redis
    image: "redis:latest"
    restart: unless-stopped

  nginx:
      container_name: nginx
      image: nginx:1.19.2-alpine
      hostname: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - "8000:80"
        - "8001:81"
      depends_on:
        - api
        - chat
        - frontend

volumes:
  postgres_data:
  redis_data:
