version: "3.1"
services:
  db:
    container_name: lah_db
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    env_file:
      - .env
  api:
    container_name: api
    build: ./backend/api
    restart: always
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    expose: 
      - "${BACKEND_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    profiles:
      - backend
  frontend:
    container_name: react
    build: ./frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    expose:
      - "${FRONTEND_PORT}"
    depends_on:
      - api
      - chat
    profiles:
      - backend

  chat:
    container_name: chat
    build:
      context: ./backend/messaging
      dockerfile: Dockerfile
    ports:
      - '${CHAT_PORT}:${CHAT_PORT}'
    restart: unless-stopped
    env_file:
      - .env
    depends_on: 
      - db   
