version: "3.1"
services:
  db:
    container_name: lah_db
    image: postgres
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - '${{ secrets.POSTGRES_PORT }}:${{ secrets.POSTGRES_PORT }}'
    env_file:
      - ./backend/api/.env.docker
  api:
    container_name: api
    build: ./backend/api
    restart: always
    ports:
      - "${{ secrets.BACKEND_PORT}}:${{ BACKEND_PORT }}"
    expose: 
      - "${{ secrets.BACKEND_PORT }}"
    env_file:
      - .env
    depends_on:
      - db
  frontend:
    container_name: react
    build: ./frontend
    restart: always
    ports:
      - "${{ secrets.FRONTEND_PORT }}:${ secrets.FRONTEND_PORT }}"
    expose:
      - "${{ secrets.FRONTEND_PORT }}"
    depends_on:
      - api
      - chat

  chat:
    container_name: chat
    build:
      context: ./chat-service 
      dockerfile: Dockerfile
    ports:
      - '${{ secrets.CHAT_PORT }}:${{ secrets.CHAT_PORT }}'
    restart: unless-stopped
    depends_on: 
      - redis 
    environment:
      REDIS_HOST: redis
      REDIS_PORT: "${{ secrets.REDIS_PORT }}"    
   
  redis:
    container_name: redis
    image: "redis:latest"
    restart: unless-stopped

  nginx:
      container_name: nginx
      image: nginx:1.19.2-alpine
      hostname: nginx
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:

      depends_on:
          - redis

volumes:
  postgres_data:
  redis_data: