name: LendAHand CI/CD

on:
  push:
    branches: [master, do-deploy]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:

  frontend_testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node Environment
        uses: actions/setup-node@v3
        with:
          node-version: "14.x"
          cache: "npm"
          # REQUIRED FOR MONOREPOS
          cache-dependency-path: frontend/npm-shrinkwrap.json

      - name: Install npm dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build --if-present
        env:
          CI: ""

      - name: Run Frontend Tests
        run: npm run test -- --coverage

  backend_testing:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend/api

    steps:
    - uses: actions/checkout@v3

    - name: Build Backend
      run: cargo build --verbose

    - name: Run Backend Tests
      run: cargo test --verbose

  build_and_push:
    runs-on: ubuntu-latest
      # Ensure test jobs pass before continuing.
    needs: [frontend_testing, backend_testing]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Build image
        run: docker-compose -f docker-compose.yml build  --no-cache

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_ACCESS_TOKEN }}

      - name: Log in to DO Container Registry
        run: doctl registry login --expiry-seconds 6000

      - name: Push image to DO Container Registry
        run: docker-compose -f docker-compose.yml push

      - name: Drop Previous Production Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /app/LendAHand            
            docker-compose -f /app/LendAHand/docker-compose.yml down
            docker system prune -af
            rm -rf ./*
            touch docker_down.txt

      - name: Copy nginx via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "nginx.conf"
          target: "/app/LendAHand"

      - name: Copy Docker-Compose via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          source: "docker-compose.prod.yml"
          target: "/app/LendAHand"

      - name: Deploy Full Stack
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /app/LendAHand
            doctl registry login
            mv docker-compose.prod.yml docker-compose.yml
            sudo docker-compose up -d --build
            touch docker_up.txt
